### PR TITLE
Support Python 3.x

### PR DESCRIPTION
**Pull request by muyuballs**
Convert Code , Supported Python 3.x

### CODE REVIEW

**Comment by gozes** [comment]
@paulchakravarti  any chance that this and PR #2  get merge any time soon?

**Comment by fimion** [comment]
@paulchakravarti 3rd vote for updating for 3.x!

**Comment by arahayrabedian** [comment]
@paulchakravarti ^^

**Comment by paulchakravarti** [comment]
Apologies for the delay getting to this. I've now added Python 3 support and uploaded a new version (0.6.1) to PyPi. I hadn't merged for a while as there were actually quite a lot more changes required to provide clean Python 2/3 support and ensure all the tests passed (the pull request broke a lot of the tests so I didn't actually merge this) however hopefully everything is now working. Would be grateful if anyone needing Python 3 support could test and raise any issues.

**Pull request closed without merging**
